get:
  operationId: routesGetAll
  summary: 全Route一覧の表示
  tags: [route]
  responses:
    200:
      description: ok
      content:
        application/json:
          schema:
            type: object
            required: [routes]
            properties:
              routes:
                type: array
                items:
                  $ref: ../components/schemas/route.yml#/Route

post:
  operationId: routesPost
  summary: Routeの作成
  tags: [route]
  description: |
    指定した名前のRouteを作成し、そのidを返す
  requestBody:
    description: Routeの情報
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/route_create.yml#/RouteCreateRequest
  responses:
    201:
      description: created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/route_create.yml#/RouteCreateResponse