[package]
name = "route-bucket-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
route-bucket-domain = { version = "0.1.0", path = "../../domain", features = ["wasm"] }
yew = "0.19.3"
