openapi: 3.0.3
info:
  title: RouteBucketBackend
  description: RouteBucketBackend
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/'
    description: development

tags:
  - name: route
    description: ルートに関するエンドポイントたち

paths:
  /routes/:
    $ref: ./paths/routes.yml
  /routes/{id}:
    $ref: ./paths/routes_by_id.yml
  /routes/{id}/add/{pos}:
    $ref: ./paths/routes_add.yml
  /routes/{id}/remove/{pos}:
    $ref: ./paths/routes_remove.yml
  /routes/{id}/clear/:
    $ref: ./paths/routes_clear.yml
  /routes/{id}/redo/:
    $ref: ./paths/routes_redo.yml
  /routes/{id}/undo/:
    $ref: ./paths/routes_undo.yml
